got_linux_task:
  container:
    image: gcc:latest
  before_build_script: .github/ci/before-install.sh
  build:script: .github/ci/build.sh

got_alpine_linux_task:
  container:
    image: alpine:latest
  script:
    - apk add build-base bison automake make autoconf libbsd-dev util-linux-dev libressl-dev zlib-dev ncurses-dev
    - .github/ci/build.sh

got_freebsd_task:
  freebsd_instance:
    image_family: freebsd-13-0
  before_build_script: .github/ci/before-install.sh
  build:script: .github/ci/build.sh

got_macos_task:
  macos_instance:
    image: monterey-xcode
  before_build_script: .github/ci/before-install.sh
  build:script: .github/ci/build.sh
